const dummyCaseData = [
  {
    caseNo: "2021-001",
    caseName: "Smith v. Johnson",
    description: "This case involves a dispute between John Smith and Michael Johnson. John Smith is the party bringing the case to the District Court. He can be contacted at 1234567890. Michael Johnson is the adverse party, represented by lawyer Emily Williams, whose contact number is 9876543210.",
    partyName: "John Smith",
    courtName: "District Court",
    partyContactNo: "1234567890",
    adversePartyName: "Michael Johnson",
    adversePartyLawyerName: "Emily Williams",
    adversePartyLawyerNo: "9876543210",
  },
  {
    caseNo: "2021-002",
    caseName: "Doe v. Roe",
    description: "This case involves a dispute between Jane Doe and John Roe. Jane Doe is the party bringing the case to the Supreme Court. She can be contacted at 5555555555. John Roe is the adverse party, represented by lawyer Robert Davis, whose contact number is 4444444444.",
    partyName: "Jane Doe",
    courtName: "Supreme Court",
    partyContactNo: "5555555555",
    adversePartyName: "John Roe",
    adversePartyLawyerName: "Robert Davis",
    adversePartyLawyerNo: "4444444444",
  },
  {
    caseNo: "2021-003",
    caseName: "Black Corp. v. White Corp.",
    description: "This case involves a dispute between Black Corporation and White Corporation. Black Corporation is the party bringing the case to the High Court. They can be contacted at 9876543210. White Corporation is the adverse party, represented by lawyer Jessica Anderson, whose contact number is 1234567890.",
    partyName: "Black Corporation",
    courtName: "High Court",
    partyContactNo: "9876543210",
    adversePartyName: "White Corporation",
    adversePartyLawyerName: "Jessica Anderson",
    adversePartyLawyerNo: "1234567890",
  },
  {
    caseNo: "2021-004",
    caseName: "Garcia v. Martinez",
    description: "This case involves a dispute between Maria Garcia and Carlos Martinez. Maria Garcia is the party bringing the case to the County Court. She can be contacted at 7777777777. Carlos Martinez is the adverse party, represented by lawyer David Thompson, whose contact number is 8888888888.",
    partyName: "Maria Garcia",
    courtName: "County Court",
    partyContactNo: "7777777777",
    adversePartyName: "Carlos Martinez",
    adversePartyLawyerName: "David Thompson",
    adversePartyLawyerNo: "8888888888",
  },
  {
    caseNo: "2021-005",
    caseName: "Brown v. Davis",
    description: "This case involves a dispute between Emily Brown and Daniel Davis. Emily Brown is the party bringing the case to the Circuit Court. She can be contacted at 2222222222. Daniel Davis is the adverse party, represented by lawyer Olivia Turner, whose contact number is 6666666666.",
    partyName: "Emily Brown",
    courtName: "Circuit Court",
    partyContactNo: "2222222222",
    adversePartyName: "Daniel Davis",
    adversePartyLawyerName: "Olivia Turner",
    adversePartyLawyerNo: "6666666666",
  },
];

export default dummyCaseData;